### ISSUE TITLE
How to: Use code completion on a variable?

### ISSUE THREAD

**Issue by seifer7** [erjobi/SuiteSnippets#1]
Hi there
This is probably a really stupid question but I'm brand new to using an IDE or Autocomplete.
Normally I use Notepad++ and just do everything myself.

I installed your extension and it works.
If I type `record.` I get the expected list of functions.
But how do I make it list the functions if I define a different variable as a `record`?
Example:
```
var myRec = record.load({
    type: record.Type.SALES_ORDER,
    id: 100
})
```

How can I make `myRec.` display the list of functions for the `Record` type?

Thank you!

**Comment by erjobi** [comment]
Not a stupid question at all.


What youll want to do is type “record.” again. Since this tool cant predict what you will name your record (in this case “myRec”) it will only show the record options when you type “record.”

Lets say you wanted to set a value after you declared myRec...

Type “record.set” and record.setValue will appear as an option. Once you highlight that option and press Tab, the “record” part of “record.setValue” will be highlighted and you can then type “myRec”

That will leave you with myRec.setValue....

Hope that helps! Let me know if you need any more help.

Essentially, always type “record.” to get the list of functions then replace the “record” with whatever variable name you declared.

**Comment by seifer7** [comment]
Thank you! This works perfectly.
